-- Migration 075: any member can say "I'll book it"; catalogue decisions made
-- after 070 went live. STAGED -- written, not applied anywhere. Applies after
-- 069 (plan_booking_owners) and 070.
--
-- Booking (owner decision 2026-09-27): claim_booking / release_booking let any
-- member of a plan take or give back the booking, as the host already could
-- through execute_plan_command 'patch' (unchanged: the host can still set or
-- clear it for anyone). plans.booking_owner stays the label everyone reads;
-- plan_booking_owners records the account (069). A member never silently
-- takes over another member's live claim -- two taps at once get one
-- "claimed" and one "taken" -- and nothing moves once the plan is booked.

begin;

create or replace function claim_booking(p_plan_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  target plans%rowtype;
  holder uuid;
  label text;
begin
  if not is_permanent_user() then
    raise exception 'Sign in required' using errcode = '42501';
  end if;
  -- Plans first, then child rows: the order every other plan write takes.
  select * into target from plans where id = p_plan_id for update;
  if target.id is null then
    return jsonb_build_object('result', 'not_found');
  end if;
  if not exists (select 1 from plan_access where plan_id = p_plan_id and user_id = auth.uid()) then
    return jsonb_build_object('result', 'not_member');
  end if;
  if target.booked is true then
    return jsonb_build_object('result', 'booked', 'booking_owner', target.booking_owner);
  end if;
  -- A claim whose account was deleted (user_id set null) is free to take.
  select user_id into holder from plan_booking_owners where plan_id = p_plan_id;
  if holder is not null and holder <> auth.uid() then
    return jsonb_build_object('result', 'taken', 'booking_owner', target.booking_owner);
  end if;
  -- The label is the caller's own profile name, never text they send.
  select nullif(clean_display_name(display_name), '') into label from people where auth_user_id = auth.uid();
  if label is null then
    return jsonb_build_object('result', 'no_profile');
  end if;
  update plans set booking_owner = label where id = p_plan_id;
  insert into plan_booking_owners (plan_id, user_id) values (p_plan_id, auth.uid())
  on conflict (plan_id) do update set user_id = excluded.user_id;
  return jsonb_build_object('result', 'claimed', 'booking_owner', label);
end; $$;
revoke all on function claim_booking(uuid) from public, anon, authenticated;
grant execute on function claim_booking(uuid) to authenticated;

create or replace function release_booking(p_plan_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  target plans%rowtype;
begin
  if not is_permanent_user() then
    raise exception 'Sign in required' using errcode = '42501';
  end if;
  select * into target from plans where id = p_plan_id for update;
  if target.id is null then
    return jsonb_build_object('result', 'not_found');
  end if;
  if not exists (select 1 from plan_access where plan_id = p_plan_id and user_id = auth.uid()) then
    return jsonb_build_object('result', 'not_member');
  end if;
  -- Booked means the reservation exists: the name stays, as leave_plan keeps it.
  if target.booked is true then
    return jsonb_build_object('result', 'booked', 'booking_owner', target.booking_owner);
  end if;
  if not exists (select 1 from plan_booking_owners where plan_id = p_plan_id and user_id = auth.uid()) then
    return jsonb_build_object('result', 'not_yours', 'booking_owner', target.booking_owner);
  end if;
  update plans set booking_owner = null where id = p_plan_id;
  delete from plan_booking_owners where plan_id = p_plan_id;
  return jsonb_build_object('result', 'released');
end; $$;
revoke all on function release_booking(uuid) from public, anon, authenticated;
grant execute on function release_booking(uuid) to authenticated;

-- BEGIN GENERATED by scripts/gen-catalogue-truth.mjs -- edit its lists, not this block
-- Catalogue decisions made after 070 was applied (070 is frozen). A retired
-- curated row leaves the deal pool, the wall and Discover; plans that already
-- hold it still read it.
update spots set visibility = 'private' where id = '20000000-0000-0000-0000-000000000002' and source = 'curated'; -- Scoopi Cafe: retired (owner decision 2026-09-27)
update spots set visibility = 'private' where id = '60000000-0000-0000-0000-000000000002' and source = 'curated'; -- Garage Dubai: retired (owner decision 2026-09-27)
-- Iris Harbour is a lounge: vibes, not shisha (owner decision 2026-09-27).
update spots set category = 'vibes', cuisine = 'Lounge'
  where id = 'd0000000-0000-0000-0000-000000000004' and source = 'curated';
-- END GENERATED

commit;
