-- Migration 090: Google place ids for reviewed curated spots.
--
-- STAGED. Generated by scripts/places-backfill.ts --write-sql from the
-- human-reviewed scripts/places-review.local.json (2026-09-29T18:01:02.520Z).
-- Requires migration 063 (the google_place_id column). Apply only with the
-- owner's approval, then record it in worklog.md the same day.
--
-- Only the place id is written: it is the one Places field Google lets us
-- store indefinitely. Names, ratings, hours and Google's coordinates are
-- NOT copied (Maps Platform terms, see docs/PLACES_INGESTION_SCOPE.md).
-- Re-run safe: each row only fills a null.

begin;

-- Aventura Parks
update public.spots set google_place_id = 'ChIJ7RC_A2BgXz4RBJKAqr4PR9g', places_synced_at = now()
  where id = '86000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Deep Dive Dubai
update public.spots set google_place_id = 'ChIJVTTIyb9pXz4RwhcoNMXJGZQ', places_synced_at = now()
  where id = '86000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Mountain Extreme
update public.spots set google_place_id = 'ChIJO1mXsjVoXz4RppyhdOAamIo', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00030e2f1de4' and source = 'curated' and google_place_id is null;

-- Sky Views Edge Walk
update public.spots set google_place_id = 'ChIJTVkwQ6xDXz4RiuQ5eA5GfVM', places_synced_at = now()
  where id = '86000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Jumeirah Public Beach
update public.spots set google_place_id = 'ChIJp-v63kRqXz4RkI_QWr9zo7o', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00000558176d' and source = 'curated' and google_place_id is null;

-- Kite Beach
update public.spots set google_place_id = 'ChIJu0nLx_9BXz4RC0A74hRtff0', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- La Mer
update public.spots set google_place_id = 'ChIJf8ZVAPhDXz4RXrmASakMieI', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Marina Beach Dubai
update public.spots set google_place_id = 'ChIJpfMHewAVXz4RqI-DL1MyIYs', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-000013154b04' and source = 'curated' and google_place_id is null;

-- Mercato Beach
update public.spots set google_place_id = 'ChIJP3syokBCXz4RQnGtNrYq2KI', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00000556954f' and source = 'curated' and google_place_id is null;

-- Nikki Beach
update public.spots set google_place_id = 'ChIJCS1uoLtDXz4R8xPbD4VJNC8', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Andreea's Beach Club
update public.spots set google_place_id = 'ChIJ809bpFJrXz4RyXDuyN8RAt8', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000295b10665' and source = 'curated' and google_place_id is null;

-- DRIFT Beach Dubai
update public.spots set google_place_id = 'ChIJtZ7bRkdrXz4R842Q9zD7s6g', places_synced_at = now()
  where id = '83000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- O Beach Dubai
update public.spots set google_place_id = 'ChIJLTs2aQBrXz4RKGOlaqdzP3I', places_synced_at = now()
  where id = '83000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Riva Beach
update public.spots set google_place_id = 'ChIJ0ch0IyxrXz4ReOrh3nY7b34', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0001a75333ad' and source = 'curated' and google_place_id is null;

-- Black Coffee by Cafe Younes
update public.spots set google_place_id = 'ChIJ-63diyZDXz4RmUtRals5YBY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000339f0a9c0' and source = 'curated' and google_place_id is null;

-- Brasserie 2.0
update public.spots set google_place_id = 'ChIJyR6tClNrXz4R0kDI1-IAiQY', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Reform Social & Grill
update public.spots set google_place_id = 'ChIJ07zymZtsXz4R1zEcs5bu4xo', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Saffron
update public.spots set google_place_id = 'ChIJEfocRj4VXz4RzZDC4qJQGxw', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- %Arabica JBR
update public.spots set google_place_id = 'ChIJueoKrtEVXz4REaPBRqQCp74', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Caffeine & Culture Cafe
update public.spots set google_place_id = 'ChIJy3Up_nNpXz4RI8DOgrKOZrc', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0001fb212036' and source = 'curated' and google_place_id is null;

-- Common Grounds
update public.spots set google_place_id = 'ChIJybFHNPFtXz4RzsKNyU9I9M8', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Home Bakery
update public.spots set google_place_id = 'ChIJzzQCUWlCXz4RGmxlehdTvPA', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00025bb4ee8e' and source = 'curated' and google_place_id is null;

-- Ijaza Cafeteria
update public.spots set google_place_id = 'ChIJM-vXh0BCXz4RfMbMjbTCTH8', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00010cb1c4b5' and source = 'curated' and google_place_id is null;

-- Levante
update public.spots set google_place_id = 'ChIJHw-mWIhdXz4R_8mBsAZYC2k', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00032c5d7f32' and source = 'curated' and google_place_id is null;

-- One Life Kitchen
update public.spots set google_place_id = 'ChIJ627xThFoXz4R49vvxoMOw8s', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- The Sum Of Us
update public.spots set google_place_id = 'ChIJ8fJbT-9CXz4RtmnvwC6kqH8', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0001045cbd5a' and source = 'curated' and google_place_id is null;

-- The Surf Café & The Sushi Bar
update public.spots set google_place_id = 'ChIJJY00JURqXz4RvBEqrAMVj98', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000143e239c6' and source = 'curated' and google_place_id is null;

-- Tom & Serg
update public.spots set google_place_id = 'ChIJj3fdMipqXz4RFMG6snLxSaY', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Al Shindagha Museum
update public.spots set google_place_id = 'ChIJv8NPy4JDXz4Rq0g_w3p4eEg', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Dubai Frame
update public.spots set google_place_id = 'ChIJQZ3ZINtCXz4RmFeoAa81MPk', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-0000170bce2f' and source = 'curated' and google_place_id is null;

-- Dubai Opera
update public.spots set google_place_id = 'ChIJkdkorypoXz4RY_9KOq__Vcg', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00001c5cdfb8' and source = 'curated' and google_place_id is null;

-- Etihad Museum
update public.spots set google_place_id = 'ChIJ-y_VQqpDXz4R1hgHMuyDNXY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00013dd0b941' and source = 'curated' and google_place_id is null;

-- Jameel Arts Centre
update public.spots set google_place_id = 'ChIJl_CSFGldXz4RhlrREDrsiZU', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Madame Tussauds Dubai
update public.spots set google_place_id = 'ChIJPWr28uEVXz4RJtT-uKWF4Gc', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00028072c86e' and source = 'curated' and google_place_id is null;

-- Mondoir Art Gallery
update public.spots set google_place_id = 'ChIJi1d1gMJpXz4R-9di63ycb28', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00027d52b2c1' and source = 'curated' and google_place_id is null;

-- Museum of the Future
update public.spots set google_place_id = 'ChIJqU_DoUtDXz4RxC8gnP8G_Ss', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- The Junction
update public.spots set google_place_id = 'ChIJoc2EyCpqXz4RECTxCGm55rs', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00024a89e98d' and source = 'curated' and google_place_id is null;

-- The Theater Dubai
update public.spots set google_place_id = 'ChIJa7q7StRDXz4RNTF35-PlXRg', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00024a89e98c' and source = 'curated' and google_place_id is null;

-- Theatre by QE2
update public.spots set google_place_id = 'ChIJfxhc7jJDXz4R2dRTPnIgGDs', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00024a8cdabc' and source = 'curated' and google_place_id is null;

-- Women's museum
update public.spots set google_place_id = 'ChIJqwETbERDXz4Rx_sTV5IMtCQ', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00011eeb00a7' and source = 'curated' and google_place_id is null;

-- House of Pops
update public.spots set google_place_id = 'ChIJhwF6iWEVXz4RSz8n__8BgF0', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0000a879c131' and source = 'curated' and google_place_id is null;

-- La Fragola
update public.spots set google_place_id = 'ChIJETWUmiloXz4RZS3SW-K_59Y', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000345777670' and source = 'curated' and google_place_id is null;

-- Sugar Bae
update public.spots set google_place_id = 'ChIJj6C6w85DXz4R_GEK1KpD9h4', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002ec6f8c61' and source = 'curated' and google_place_id is null;

-- 3Fils
update public.spots set google_place_id = 'ChIJc_qkbD5CXz4RjckbjFAB3eM', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Al Khayma Heritage Restaurant
update public.spots set google_place_id = 'ChIJl6Wlj3JDXz4RiuVGW1AttdY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-000019f1f364' and source = 'curated' and google_place_id is null;

-- Bu Qtair
update public.spots set google_place_id = 'ChIJlbbiwENqXz4RYs-mK1C-G8o', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Goose & Gander
update public.spots set google_place_id = 'ChIJIWNdbvlrXz4RkuG95vLl5LM', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000348b497a3' and source = 'curated' and google_place_id is null;

-- Ibn AlBahr
update public.spots set google_place_id = 'ChIJjeQxxIrQXT4RxnrrChED7JY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000211b24654' and source = 'curated' and google_place_id is null;

-- Kapadokya Turkish Kitchen
update public.spots set google_place_id = 'ChIJ-0IK5aJrXz4ReotzQpAyVEg', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00018058f279' and source = 'curated' and google_place_id is null;

-- Mythos
update public.spots set google_place_id = 'ChIJXzeVJKlsXz4RaRYtd-L-GxE', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00013850bf99' and source = 'curated' and google_place_id is null;

-- NAMMOS Dubai
update public.spots set google_place_id = 'ChIJV0slHPhDXz4RoF95ax_zNg4', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00024148aa72' and source = 'curated' and google_place_id is null;

-- Pierchic
update public.spots set google_place_id = 'ChIJl3M6MVVqXz4RiAR6l5IVMC0', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-000007ab7716' and source = 'curated' and google_place_id is null;

-- Ravi Restaurant
update public.spots set google_place_id = 'ChIJN81uvipDXz4RH_4cyTocRMI', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Reif Japanese Kushiyaki
update public.spots set google_place_id = 'ChIJN0PuVXJpXz4RTi-IEGAvito', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Taraf Restaurant and Cafe
update public.spots set google_place_id = 'ChIJ2UBHD6RDXz4RtA9mRrWRKNY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000289c78744' and source = 'curated' and google_place_id is null;

-- The Maine Oyster Bar and Grill
update public.spots set google_place_id = 'ChIJEZuNlVcTXz4RQmo0U27cMG4', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0000f466cf94' and source = 'curated' and google_place_id is null;

-- Tresind Studio
update public.spots set google_place_id = 'ChIJcfzwzo0TXz4RyQpaHkMBWsE', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000005' and source = 'curated' and google_place_id is null;

-- Anantara World Islands Dubai
update public.spots set google_place_id = 'ChIJobMv6VRBXz4ROY0E7e4_fMk', places_synced_at = now()
  where id = '8b000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Escape the Room Dubai
update public.spots set google_place_id = 'ChIJEw0tt3JCXz4Rl2ITtvpO9vY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00010120a61d' and source = 'curated' and google_place_id is null;

-- Hysteria Dubai Mall
update public.spots set google_place_id = 'ChIJr17TmYJCXz4R9-0fFHz7XcY', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00016708b192' and source = 'curated' and google_place_id is null;

-- 3D Blacklight Minigolf Dubai
update public.spots set google_place_id = 'ChIJpSePkqoUXz4R12VZctYMV1E', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002fa5ad335' and source = 'curated' and google_place_id is null;

-- Dubai Aquarium & Underwater Zoo
update public.spots set google_place_id = 'ChIJRcbZaklDXz4RKd2od-FVCyM', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000085e4a85c' and source = 'curated' and google_place_id is null;

-- Dubai Crocodile Park
update public.spots set google_place_id = 'ChIJe1MWL_xgXz4RW8NUf1-VuWo', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-0000260c761b' and source = 'curated' and google_place_id is null;

-- Dubai Garden Glow
update public.spots set google_place_id = 'ChIJwyGLXcFCXz4RthyG7eNRSRk', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000174ce3d18' and source = 'curated' and google_place_id is null;

-- Dubai Safari Park
update public.spots set google_place_id = 'ChIJ7S8tVt9hXz4RqJoZ8a14E2E', places_synced_at = now()
  where id = '8a000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- KidZania Dubai
update public.spots set google_place_id = 'ChIJiykKVyhoXz4RPNxlUTJsgyY', places_synced_at = now()
  where id = '8a000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Ski Dubai
update public.spots set google_place_id = 'ChIJ____775rXz4Rbvg2X19nuxI', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000085e4d2f0' and source = 'curated' and google_place_id is null;

-- Bounce
update public.spots set google_place_id = 'ChIJgzxnBStqXz4R7uo1SnN_dGI', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Brass Monkey
update public.spots set google_place_id = 'ChIJy76ImJJDXz4R0FL806mi97I', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002da3bef2e' and source = 'curated' and google_place_id is null;

-- Dubai Bowling Centre
update public.spots set google_place_id = 'ChIJUReYjsZpXz4RF3jSb9VMW7I', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Hub Zero
update public.spots set google_place_id = 'ChIJpYjl_GRCXz4Rv21AyZyqDKw', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- PlayDXB
update public.spots set google_place_id = 'ChIJB_4WeyhoXz4RkBLYAU3zHOs', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00016708b191' and source = 'curated' and google_place_id is null;

-- The Smash Room
update public.spots set google_place_id = 'ChIJnU3TMuNrXz4RGhd4Pi_IuTc', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Bla Bla
update public.spots set google_place_id = 'ChIJK0N9FFwTXz4R-gmJj0b9GZg', places_synced_at = now()
  where id = '70000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Kono's Karaoke
update public.spots set google_place_id = 'ChIJBRjwtOZDXz4RcdRI6njkdGU', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00031a2ef171' and source = 'curated' and google_place_id is null;

-- Lucky Voice
update public.spots set google_place_id = 'ChIJeQNR3XZrXz4RUMcUvKYsNVo', places_synced_at = now()
  where id = '70000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- McGettigan's
update public.spots set google_place_id = 'ChIJwYVRl61sXz4R1hMrE6l_RfY', places_synced_at = now()
  where id = '70000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Hard Rock Cafe Dubai
update public.spots set google_place_id = 'ChIJV3up52pDXz4R4fLkWSxbSuM', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Q's Bar and Lounge
update public.spots set google_place_id = 'ChIJGXbqKGldXz4RjottSe5mxFo', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- The Fridge
update public.spots set google_place_id = 'ChIJc4yfI0VpXz4R6UDvGFep2zA', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Cinema Akil
update public.spots set google_place_id = 'ChIJA363yypqXz4R0Tl8t80quQA', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Cinemacity
update public.spots set google_place_id = 'ChIJOQCMtShpXz4Rd2MON_xUl-M', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002d605d22b' and source = 'curated' and google_place_id is null;

-- Reel Cinemas
update public.spots set google_place_id = 'ChIJ87sPdihoXz4RuOf3XNRmFn4', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Roxy Cinemas
update public.spots set google_place_id = 'ChIJwSTWrGVCXz4RkpqSy1JiiQs', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- VOX Cinemas
update public.spots set google_place_id = 'ChIJFRfpr75rXz4Rsr1pyFsGTYg', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- BLU Dubai
update public.spots set google_place_id = 'ChIJv1EMrHFpXz4Rshi0jsu8kxY', places_synced_at = now()
  where id = '81000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Chameleon
update public.spots set google_place_id = 'ChIJxXLGnHBrXz4RYFdyt7PnAcQ', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0000eeb8fc68' and source = 'curated' and google_place_id is null;

-- Soho Garden Meydan
update public.spots set google_place_id = 'ChIJ1-snMIloXz4RWytdBKS5Xd0', places_synced_at = now()
  where id = '81000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- SOT Dubai - Nightclub & Lounge
update public.spots set google_place_id = 'ChIJGabC41RdXz4R4uQuglRAL_g', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00028ec76ee1' and source = 'curated' and google_place_id is null;

-- Al Barsha Pond Park
update public.spots set google_place_id = 'ChIJhyp_3IxrXz4RSKXQzmedlGc', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00002f23e566' and source = 'curated' and google_place_id is null;

-- Al Qudra Lakes
update public.spots set google_place_id = 'ChIJreY1bgCDXz4RHWEOpL59gTs', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Dubai Marina Walk
update public.spots set google_place_id = 'ChIJX47nvlBrXz4RVW5QiQ0Xvjw', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Hatta Hill Park
update public.spots set google_place_id = 'ChIJ2QM9b9ke9T4RHQ0GRDDAZgk', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00000bf72ba5' and source = 'curated' and google_place_id is null;

-- Quranic Park
update public.spots set google_place_id = 'ChIJH57sCE5hXz4RWDXUqcs-PUo', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00001b8e6e2b' and source = 'curated' and google_place_id is null;

-- The Green Planet
update public.spots set google_place_id = 'ChIJ9aSXmGVCXz4RQJArGtVv0dg', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Padel Art
update public.spots set google_place_id = 'ChIJUQveXrdpXz4RTwHn8DBjquE', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Padel Pro One Central
update public.spots set google_place_id = 'ChIJSZwLMVJDXz4RSffqb9vKTFQ', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- World Padel Academy Dubai
update public.spots set google_place_id = 'ChIJZ0hgg45pXz4RFSkePMHBglk', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Shimmers
update public.spots set google_place_id = 'ChIJAY8DDFVqXz4Rdm15Lg7eaiw', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- SoBe
update public.spots set google_place_id = 'ChIJI-LFDg4VXz4RVTKmqp7vCkA', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Dragon Mart
update public.spots set google_place_id = 'ChIJmRRTnd1hXz4RycOWdC2qclI', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-000005448350' and source = 'curated' and google_place_id is null;

-- Dubai Design District
update public.spots set google_place_id = 'ChIJrzQxexJoXz4R5dtNIYkTGm8', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Dubai Hills Mall
update public.spots set google_place_id = 'ChIJ7d_LEEJvXz4R8oq3hLV_PmQ', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00002f8befcf' and source = 'curated' and google_place_id is null;

-- Mall of the Emirates
update public.spots set google_place_id = 'ChIJnTOfw75rXz4RTBV1aGLlr0c', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Mirdif City Center
update public.spots set google_place_id = 'ChIJHWrMCLRgXz4R11IK8CvPJJE', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00000647a7f6' and source = 'curated' and google_place_id is null;

-- Souk Madinat Jumeirah
update public.spots set google_place_id = 'ChIJORSp9gBCXz4RtnTCn-ul3mo', places_synced_at = now()
  where id = 'c0890000-0000-0000-0002-00000c140405' and source = 'curated' and google_place_id is null;

-- The Dubai Mall
update public.spots set google_place_id = 'ChIJB1zIKShoXz4RnbaTPPup7aU', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Dubai Racing Club
update public.spots set google_place_id = 'ChIJezjAtudDXz4RSVAfyxDh0HQ', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002eec871d0' and source = 'curated' and google_place_id is null;

-- InSportz Club
update public.spots set google_place_id = 'ChIJBac6Q8VrXz4RV_dY53R_RC0', places_synced_at = now()
  where id = '60000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Just Play
update public.spots set google_place_id = 'ChIJSR4AbypqXz4RdanUkloqoqg', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0002651a49ce' and source = 'curated' and google_place_id is null;

-- The Huddle Sports Bar
update public.spots set google_place_id = 'ChIJwdOLquprXz4RK2SBTP90gvM', places_synced_at = now()
  where id = '60000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Bar Du Port Dubai
update public.spots set google_place_id = 'ChIJF7UAVslrXz4R1aYbpAQLeb0', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00024a3e7239' and source = 'curated' and google_place_id is null;

-- Brooklyn Bar
update public.spots set google_place_id = 'ChIJl4RhnwFrXz4RJXsuvP7jM5U', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00034dbba096' and source = 'curated' and google_place_id is null;

-- Buddha Bar
update public.spots set google_place_id = 'ChIJtwdWaFFrXz4RnACV7nu-vq8', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000248df7c72' and source = 'curated' and google_place_id is null;

-- CÉ LA VI
update public.spots set google_place_id = 'ChIJfQZqMTJDXz4RAzXhbWHDkYE', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Iris Harbour
update public.spots set google_place_id = 'ChIJyyxXIVFrXz4ROqx6UUQNBB0', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Koko Bay
update public.spots set google_place_id = 'ChIJ-Vi4PIRrXz4RPaz-YtOFX5s', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Peacock Alley DIFC
update public.spots set google_place_id = 'ChIJ967nSwVDXz4RGrNQFrexzpk', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00020fde20fa' and source = 'curated' and google_place_id is null;

-- Pure Sky Lounge & Dining
update public.spots set google_place_id = 'ChIJkeFnX6oUXz4R7dlxBC84gXc', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0001459ba94f' and source = 'curated' and google_place_id is null;

-- St. Trop DIFC
update public.spots set google_place_id = 'ChIJdUD1eUlDXz4RAwuAsn4hRoU', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-00020fde09a1' and source = 'curated' and google_place_id is null;

-- Terra Solis
update public.spots set google_place_id = 'ChIJadbONb99Xz4RTYgDWMDE-Ls', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- The Nine
update public.spots set google_place_id = 'ChIJmR5wDx5dXz4R6i8P-e8WWlg', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- The Rose and Crown Dubai
update public.spots set google_place_id = 'ChIJvUgUi1xCXz4R5ypAt2DFaDQ', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-000108d938db' and source = 'curated' and google_place_id is null;

-- Trader Vic's
update public.spots set google_place_id = 'ChIJRcbZaklDXz4RnJp3TKvtrZc', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0001cdbb1755' and source = 'curated' and google_place_id is null;

-- Warehouse
update public.spots set google_place_id = 'ChIJ88uq2hpdXz4Rc-OdoLqmH1Y', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0000de07cf66' and source = 'curated' and google_place_id is null;

-- Wavebreaker Beachside Restaurant
update public.spots set google_place_id = 'ChIJfVH5iKoUXz4RU9GRvx-4XM0', places_synced_at = now()
  where id = 'c0890000-0000-0000-0001-0000e6f99981' and source = 'curated' and google_place_id is null;

-- Aquaventure World
update public.spots set google_place_id = 'ChIJRcbZaklDXz4RXfL8v3kej7c', places_synced_at = now()
  where id = '84000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Wild Wadi Waterpark
update public.spots set google_place_id = 'ChIJh7LUHlFqXz4RbIRg-g5fo-E', places_synced_at = now()
  where id = '84000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Talise Spa Madinat Jumeirah
update public.spots set google_place_id = 'ChIJLyoOEKtrXz4RC68to61RK8Q', places_synced_at = now()
  where id = '88000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- The Hundred Wellness Centre
update public.spots set google_place_id = 'ChIJRW9j9TNdXz4Rlx-MnVXXRko', places_synced_at = now()
  where id = '88000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

commit;
