-- Migration 076: Google place ids for reviewed curated spots.
--
-- STAGED. Generated by scripts/places-backfill.ts --write-sql from the
-- human-reviewed scripts/places-review.local.json (2026-09-27T16:43:03.547Z).
-- Requires migration 063 (the google_place_id column). Apply only with the
-- owner's approval, then record it in worklog.md the same day.
--
-- Only the place id is written: it is the one Places field Google lets us
-- store indefinitely. Names, ratings, hours and Google's coordinates are
-- NOT copied (Maps Platform terms, see docs/PLACES_INGESTION_SCOPE.md).
-- Re-run safe: each row only fills a null.

begin;

-- Aventura Parks
update public.spots set google_place_id = 'ChIJ7RC_A2BgXz4RBJKAqr4PR9g', places_synced_at = now()
  where id = '86000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Deep Dive Dubai
update public.spots set google_place_id = 'ChIJVTTIyb9pXz4RwhcoNMXJGZQ', places_synced_at = now()
  where id = '86000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Cove Beach
update public.spots set google_place_id = 'ChIJZTY4l1pqXz4RhMJsk4xvbgk', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Kite Beach
update public.spots set google_place_id = 'ChIJu0nLx_9BXz4RC0A74hRtff0', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- La Mer
update public.spots set google_place_id = 'ChIJf8ZVAPhDXz4RXrmASakMieI', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Nikki Beach
update public.spots set google_place_id = 'ChIJCS1uoLtDXz4R8xPbD4VJNC8', places_synced_at = now()
  where id = '40000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- DRIFT Beach Dubai
update public.spots set google_place_id = 'ChIJtZ7bRkdrXz4R842Q9zD7s6g', places_synced_at = now()
  where id = '83000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Brasserie 2.0
update public.spots set google_place_id = 'ChIJyR6tClNrXz4R0kDI1-IAiQY', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Reform Social & Grill
update public.spots set google_place_id = 'ChIJ07zymZtsXz4R1zEcs5bu4xo', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Saffron
update public.spots set google_place_id = 'ChIJEfocRj4VXz4RzZDC4qJQGxw', places_synced_at = now()
  where id = '10000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- %Arabica JBR
update public.spots set google_place_id = 'ChIJueoKrtEVXz4REaPBRqQCp74', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Common Grounds
update public.spots set google_place_id = 'ChIJybFHNPFtXz4RzsKNyU9I9M8', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- One Life Kitchen
update public.spots set google_place_id = 'ChIJ627xThFoXz4R49vvxoMOw8s', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Tom & Serg
update public.spots set google_place_id = 'ChIJj3fdMipqXz4RFMG6snLxSaY', places_synced_at = now()
  where id = 'c0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Al Shindagha Museum
update public.spots set google_place_id = 'ChIJv8NPy4JDXz4Rq0g_w3p4eEg', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Jameel Arts Centre
update public.spots set google_place_id = 'ChIJl_CSFGldXz4RhlrREDrsiZU', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Museum of the Future
update public.spots set google_place_id = 'ChIJqU_DoUtDXz4RxC8gnP8G_Ss', places_synced_at = now()
  where id = '87000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- 3Fils
update public.spots set google_place_id = 'ChIJc_qkbD5CXz4RjckbjFAB3eM', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Bu Qtair
update public.spots set google_place_id = 'ChIJlbbiwENqXz4RYs-mK1C-G8o', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Ravi Restaurant
update public.spots set google_place_id = 'ChIJN81uvipDXz4RH_4cyTocRMI', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Reif Japanese Kushiyaki
update public.spots set google_place_id = 'ChIJN0PuVXJpXz4RTi-IEGAvito', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Tresind Studio
update public.spots set google_place_id = 'ChIJcfzwzo0TXz4RyQpaHkMBWsE', places_synced_at = now()
  where id = 'a0000000-0000-0000-0000-000000000005' and source = 'curated' and google_place_id is null;

-- Dubai Safari Park
update public.spots set google_place_id = 'ChIJ7S8tVt9hXz4RqJoZ8a14E2E', places_synced_at = now()
  where id = '8a000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- KidZania Dubai
update public.spots set google_place_id = 'ChIJiykKVyhoXz4RPNxlUTJsgyY', places_synced_at = now()
  where id = '8a000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Bounce
update public.spots set google_place_id = 'ChIJgzxnBStqXz4R7uo1SnN_dGI', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Dubai Bowling Centre
update public.spots set google_place_id = 'ChIJUReYjsZpXz4RF3jSb9VMW7I', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Hub Zero
update public.spots set google_place_id = 'ChIJpYjl_GRCXz4Rv21AyZyqDKw', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- The Smash Room
update public.spots set google_place_id = 'ChIJnU3TMuNrXz4RGhd4Pi_IuTc', places_synced_at = now()
  where id = 'f0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Lucky Voice
update public.spots set google_place_id = 'ChIJeQNR3XZrXz4RUMcUvKYsNVo', places_synced_at = now()
  where id = '70000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- McGettigan's
update public.spots set google_place_id = 'ChIJwYVRl61sXz4R1hMrE6l_RfY', places_synced_at = now()
  where id = '70000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Hard Rock Cafe Dubai
update public.spots set google_place_id = 'ChIJV3up52pDXz4R4fLkWSxbSuM', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Q's Bar and Lounge
update public.spots set google_place_id = 'ChIJGXbqKGldXz4RjottSe5mxFo', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- The Fridge
update public.spots set google_place_id = 'ChIJc4yfI0VpXz4R6UDvGFep2zA', places_synced_at = now()
  where id = '82000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Cinema Akil
update public.spots set google_place_id = 'ChIJA363yypqXz4R0Tl8t80quQA', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Reel Cinemas
update public.spots set google_place_id = 'ChIJ87sPdihoXz4RuOf3XNRmFn4', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Roxy Cinemas
update public.spots set google_place_id = 'ChIJwSTWrGVCXz4RkpqSy1JiiQs', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- VOX Cinemas
update public.spots set google_place_id = 'ChIJFRfpr75rXz4Rsr1pyFsGTYg', places_synced_at = now()
  where id = 'e0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- BLU Dubai
update public.spots set google_place_id = 'ChIJv1EMrHFpXz4Rshi0jsu8kxY', places_synced_at = now()
  where id = '81000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Soho Garden Meydan
update public.spots set google_place_id = 'ChIJ1-snMIloXz4RWytdBKS5Xd0', places_synced_at = now()
  where id = '81000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Al Qudra Lakes
update public.spots set google_place_id = 'ChIJreY1bgCDXz4RHWEOpL59gTs', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Dubai Marina Walk
update public.spots set google_place_id = 'ChIJX47nvlBrXz4RVW5QiQ0Xvjw', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- The Green Planet
update public.spots set google_place_id = 'ChIJ9aSXmGVCXz4RQJArGtVv0dg', places_synced_at = now()
  where id = '50000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Padel Art
update public.spots set google_place_id = 'ChIJUQveXrdpXz4RTwHn8DBjquE', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Padel Pro One Central
update public.spots set google_place_id = 'ChIJSZwLMVJDXz4RSffqb9vKTFQ', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- World Padel Academy Dubai
update public.spots set google_place_id = 'ChIJZ0hgg45pXz4RFSkePMHBglk', places_synced_at = now()
  where id = '85000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- QDs
update public.spots set google_place_id = 'ChIJq6pq0MxcXz4ReHPXV4Q5uYg', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Shimmers
update public.spots set google_place_id = 'ChIJAY8DDFVqXz4Rdm15Lg7eaiw', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- SoBe
update public.spots set google_place_id = 'ChIJI-LFDg4VXz4RVTKmqp7vCkA', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- Dubai Design District
update public.spots set google_place_id = 'ChIJrzQxexJoXz4R5dtNIYkTGm8', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Mall of the Emirates
update public.spots set google_place_id = 'ChIJnTOfw75rXz4RTBV1aGLlr0c', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- The Dubai Mall
update public.spots set google_place_id = 'ChIJB1zIKShoXz4RnbaTPPup7aU', places_synced_at = now()
  where id = '89000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- InSportz Club
update public.spots set google_place_id = 'ChIJBac6Q8VrXz4RV_dY53R_RC0', places_synced_at = now()
  where id = '60000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- The Huddle Sports Bar
update public.spots set google_place_id = 'ChIJwdOLquprXz4RK2SBTP90gvM', places_synced_at = now()
  where id = '60000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- CÉ LA VI
update public.spots set google_place_id = 'ChIJfQZqMTJDXz4RAzXhbWHDkYE', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Iris Harbour
update public.spots set google_place_id = 'ChIJyyxXIVFrXz4ROqx6UUQNBB0', places_synced_at = now()
  where id = 'd0000000-0000-0000-0000-000000000004' and source = 'curated' and google_place_id is null;

-- Koko Bay
update public.spots set google_place_id = 'ChIJ-Vi4PIRrXz4RPaz-YtOFX5s', places_synced_at = now()
  where id = '30000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- AquaFun Dubai
update public.spots set google_place_id = 'ChIJGUY7IBNbXz4R0zmKCH9WDiI', places_synced_at = now()
  where id = '84000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Aquaventure World
update public.spots set google_place_id = 'ChIJRcbZaklDXz4RXfL8v3kej7c', places_synced_at = now()
  where id = '84000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- Wild Wadi Waterpark
update public.spots set google_place_id = 'ChIJh7LUHlFqXz4RbIRg-g5fo-E', places_synced_at = now()
  where id = '84000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

-- SEVEN Wellness Club
update public.spots set google_place_id = 'ChIJVYHnt8ZpXz4Ry6O9cWEiyZk', places_synced_at = now()
  where id = '88000000-0000-0000-0000-000000000003' and source = 'curated' and google_place_id is null;

-- Talise Spa Madinat Jumeirah
update public.spots set google_place_id = 'ChIJLyoOEKtrXz4RC68to61RK8Q', places_synced_at = now()
  where id = '88000000-0000-0000-0000-000000000001' and source = 'curated' and google_place_id is null;

-- The Hundred Wellness Centre
update public.spots set google_place_id = 'ChIJRW9j9TNdXz4Rlx-MnVXXRko', places_synced_at = now()
  where id = '88000000-0000-0000-0000-000000000002' and source = 'curated' and google_place_id is null;

commit;
