import { PLACE_ID_PATTERN } from "./client.ts";

// Generates the STAGED data migrations from a human-reviewed backfill file.
// Every value is validated against a strict pattern first AND quoted, so a
// hostile or garbled API value is refused rather than escaped into SQL; the
// quoting is the second line, not the only one. Comments are sanitised too:
// a newline in a venue name inside a `--` comment would end the comment and
// turn the rest of the name into SQL.

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const PHOTO_FILE = /^[0-9a-f]{32}\.(jpg|png|webp)$/;

export function sqlLiteral(value: string): string {
  if (value.includes("\u0000")) throw new Error("NUL byte in a SQL literal.");
  return `'${value.replace(/'/g, "''")}'`;
}

export function sqlComment(value: string): string {
  // Control chars (incl. CR/LF/U+2028-9) and block-comment markers out.
  return value.replace(/[\u0000-\u001f\u007f\u2028\u2029]/g, " ").replace(/\/\*|\*\//g, " ").slice(0, 120).trim();
}

export interface ApprovedPlaceId {
  spotId: string;
  spotName: string;
  placeId: string;
}

export interface ApprovedPhoto {
  spotId: string;
  spotName: string;
  file: string; // e.g. "a0000000000000000000000000000005.jpg" -- see photoFileName
  sourcePage: string;
}

// Hyphen-free, because the dashboard stripped the hyphens off the last
// upload's object keys and migration 039 had to be rewritten to match.
export function photoFileName(spotId: string, contentType: string): string {
  if (!UUID.test(spotId)) throw new Error(`Not a spot id: ${spotId}`);
  const ext = contentType === "image/png" ? "png" : contentType === "image/webp" ? "webp" : "jpg";
  return `${spotId.replace(/-/g, "").toLowerCase()}.${ext}`;
}

// Public object URL base, e.g.
// https://<ref>.supabase.co/storage/v1/object/public/spot-photos/
export function storageBase(supabaseUrl: string): string {
  const url = new URL(supabaseUrl);
  if (url.protocol !== "https:" && url.hostname !== "127.0.0.1" && url.hostname !== "localhost") {
    throw new Error("Storage base must be https.");
  }
  return `${url.origin}/storage/v1/object/public/spot-photos/`;
}

function assertUniquePlaceIds(rows: ApprovedPlaceId[]): void {
  const seen = new Map<string, string>();
  for (const row of rows) {
    const other = seen.get(row.placeId);
    // The unique index would abort the whole migration halfway; refuse to
    // write one that cannot apply, and say which two spots collided.
    if (other && other !== row.spotId) {
      throw new Error(`Two spots matched the same place (${row.placeId}): ${other} and ${row.spotId}. Reject one in the review file.`);
    }
    seen.set(row.placeId, row.spotId);
  }
}

function header(number: number, title: string, lines: string[]): string {
  return [`-- Migration ${String(number).padStart(3, "0")}: ${title}`, "--", ...lines.map((l) => (l ? `-- ${l}` : "--")), ""].join("\n");
}

export function placeIdMigration(number: number, rows: ApprovedPlaceId[], generatedAt: string): string {
  assertUniquePlaceIds(rows);
  const body = rows.map((row) => {
    if (!UUID.test(row.spotId)) throw new Error(`Not a spot id: ${row.spotId}`);
    if (!PLACE_ID_PATTERN.test(row.placeId)) throw new Error(`Not a place id: ${row.placeId}`);
    return [
      `-- ${sqlComment(row.spotName)}`,
      `update public.spots set google_place_id = ${sqlLiteral(row.placeId)}, places_synced_at = now()`,
      `  where id = ${sqlLiteral(row.spotId.toLowerCase())} and source = 'curated' and google_place_id is null;`,
    ].join("\n");
  });
  return header(number, "Google place ids for reviewed curated spots.", [
    "STAGED. Generated by scripts/places-backfill.ts --write-sql from the",
    `human-reviewed scripts/places-review.local.json (${sqlComment(generatedAt)}).`,
    "Requires migration 063 (the google_place_id column). Apply only with the",
    "owner's approval, then record it in worklog.md the same day.",
    "",
    "Only the place id is written: it is the one Places field Google lets us",
    "store indefinitely. Names, ratings, hours and Google's coordinates are",
    "NOT copied (Maps Platform terms, see docs/PLACES_INGESTION_SCOPE.md).",
    "Re-run safe: each row only fills a null.",
  ]) + "\nbegin;\n\n" + body.join("\n\n") + "\n\ncommit;\n";
}

export function photoMigration(number: number, rows: ApprovedPhoto[], base: string, generatedAt: string): string {
  if (!/^https?:\/\/[^/]+\/storage\/v1\/object\/public\/spot-photos\/$/.test(base)) throw new Error("Unexpected storage base.");
  const body = rows.map((row) => {
    if (!UUID.test(row.spotId)) throw new Error(`Not a spot id: ${row.spotId}`);
    if (!PHOTO_FILE.test(row.file) || !row.file.startsWith(row.spotId.replace(/-/g, "").toLowerCase())) {
      throw new Error(`Unexpected photo file name: ${row.file}`);
    }
    return [
      `-- ${sqlComment(row.spotName)} -- venue's own og:image, from ${sqlComment(row.sourcePage)}`,
      `update public.spots set photo_url = ${sqlLiteral(base + row.file)}, photo_source = 'venue_site', photo_attribution = null`,
      `  where id = ${sqlLiteral(row.spotId.toLowerCase())} and source = 'curated' and photo_url is null;`,
    ].join("\n");
  });
  return header(number, "Venue-site photos for curated spots (from the Places website link).", [
    "STAGED. Generated by scripts/places-backfill.ts --write-sql.",
    `Source: scripts/places-review.local.json (${sqlComment(generatedAt)}).`,
    "",
    "THE FILES MUST BE IN THE LIVE spot-photos BUCKET FIRST. Upload exactly the",
    "files listed in scripts/places-photos.local/UPLOAD.json (not the whole",
    "folder -- it also holds unapproved downloads) via the Supabase dashboard,",
    "names unchanged, then run scripts/check-spot-photo-urls.sh. Running this",
    "first points cards at 404s (same process as migration 039).",
    "",
    "Each image is the venue's own og:image, so photo_source = 'venue_site'",
    "and no third-party credit is owed (migration 038). Re-run safe; each",
    "row only fills a null, and one bad photo is removed by nulling its row.",
  ]) + "\nbegin;\n\n" + body.join("\n\n") + "\n\ncommit;\n";
}

// Next free migration number. Numbers are never reused, including gaps that
// were claimed on another branch -- so this is max + 1, not the first gap.
export function nextMigrationNumber(fileNames: string[], floor = 62): number {
  let max = floor;
  for (const name of fileNames) {
    const found = /^migration-(\d{3})-/.exec(name);
    if (found) max = Math.max(max, Number(found[1]));
  }
  return max + 1;
}
